"""Optional, failure-tolerant Weights & Biases logging for HMOE-SAM3."""

from __future__ import annotations

import copy
import argparse
import os
import re
import warnings
from pathlib import Path
from typing import Any, Mapping, Optional

import torch


_SECRET_KEYS = {
    "api_key",
    "apikey",
    "wandb_api_key",
    "wandb_key",
    "wandb.key",
    "wandb.api_key",
    "wanb_api_key",
}
_SECRET_FRAGMENTS = ("password", "passwd", "secret", "token")
_PRIVATE_KEY_FRAGMENTS = ("patient_id", "patient_ids")
_PATH_FRAGMENTS = ("checkpoint",)
_PATH_SUFFIXES = ("_path", "_root", "_dir", "_file", "_json")


def _normalized_key(key: Any) -> str:
    return str(key).strip().lower().replace("-", "_")


def _is_sensitive_key(key: Any) -> bool:
    normalized = _normalized_key(key)
    return (
        normalized in _SECRET_KEYS
        or normalized.upper() == "WANDB_API_KEY"
        or any(fragment in normalized for fragment in _SECRET_FRAGMENTS)
    )


def _is_path_key(key: Any) -> bool:
    normalized = _normalized_key(key)
    return (
        normalized in {"data_dir", "output_dir", "wandb_dir"}
        or normalized.endswith(_PATH_SUFFIXES)
        or any(fragment in normalized for fragment in _PATH_FRAGMENTS)
    )


def _is_private_key(key: Any) -> bool:
    normalized = _normalized_key(key)
    return any(fragment in normalized for fragment in _PRIVATE_KEY_FRAGMENTS)


def _looks_like_absolute_path(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    return value.startswith(("/", "\\")) or bool(
        re.match(r"^[A-Za-z]:[\\/]", value)
    )


def sanitize_config(config: Any, remove_paths: bool = True) -> Any:
    """Return a deep, serializable copy without credentials or raw paths.

    Sensitive entries are removed rather than masked so secrets cannot enter a
    W&B config, checkpoint, JSON/YAML backup, or exception generated by W&B.
    """

    if isinstance(config, Mapping):
        clean = {}
        for key, value in config.items():
            if _is_sensitive_key(key) or (
                remove_paths and (_is_path_key(key) or _is_private_key(key))
            ):
                continue
            if remove_paths and _looks_like_absolute_path(value):
                continue
            clean[str(key)] = sanitize_config(value, remove_paths=remove_paths)
        return clean
    if isinstance(config, (list, tuple)):
        return [
            sanitize_config(value, remove_paths=remove_paths)
            for value in config
            if not remove_paths or not _looks_like_absolute_path(value)
        ]
    if isinstance(config, Path):
        return None
    if torch.is_tensor(config):
        if config.numel() == 1:
            return config.detach().float().item()
        return None
    if isinstance(config, (str, int, float, bool)) or config is None:
        return copy.deepcopy(config)
    return str(config)


def to_scalar(value: Any) -> Optional[float]:
    """Convert an unambiguous scalar metric without mutating its source."""

    if torch.is_tensor(value):
        if value.numel() != 1:
            return None
        return float(value.detach().float().item())
    if isinstance(value, bool):
        return float(value)
    if isinstance(value, (int, float)):
        return float(value)
    return None


def flatten_metrics(metrics: Mapping[str, Any], prefix: str = "") -> dict[str, float]:
    """Flatten nested scalar metric mappings using slash-separated names."""

    flattened: dict[str, float] = {}
    for key, value in metrics.items():
        name = f"{prefix}/{key}" if prefix else str(key)
        if isinstance(value, Mapping):
            flattened.update(flatten_metrics(value, name))
            continue
        scalar = to_scalar(value)
        if scalar is not None:
            flattened[name] = scalar
    return flattened


def _config_value(
    args: Any,
    config: Mapping[str, Any],
    name: str,
    default: Any,
    env_name: Optional[str] = None,
) -> Any:
    cli_value = getattr(args, name, None)
    if cli_value is not None:
        return cli_value
    wandb_config = config.get("wandb", {}) or {}
    if name in wandb_config:
        return wandb_config[name]
    if name in config:
        return config[name]
    if env_name and os.environ.get(env_name) not in (None, ""):
        return os.environ[env_name]
    return default


def _as_bool(value: Any) -> bool:
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"1", "true", "yes", "on"}:
            return True
        if normalized in {"0", "false", "no", "off", ""}:
            return False
        raise ValueError(f"Invalid boolean value: {value!r}")
    return bool(value)


def add_wandb_arguments(parser: argparse.ArgumentParser) -> None:
    """Add optional W&B CLI flags without changing default training behavior."""

    parser.add_argument(
        "--use-wandb",
        action="store_true",
        default=None,
        help="Enable Weights & Biases logging.",
    )
    parser.add_argument(
        "--wandb-api-key",
        type=str,
        default=None,
        help="Optional plaintext W&B API key; WANDB_API_KEY is also supported.",
    )
    parser.add_argument("--wandb-project", type=str, default=None)
    parser.add_argument("--wandb-entity", type=str, default=None)
    parser.add_argument("--wandb-name", type=str, default=None)
    parser.add_argument("--wandb-group", type=str, default=None)
    parser.add_argument("--wandb-tags", nargs="*", default=None)
    parser.add_argument(
        "--wandb-mode",
        choices=["online", "offline", "disabled"],
        default=None,
    )
    parser.add_argument("--wandb-dir", type=str, default=None)
    parser.add_argument("--wandb-log-interval", type=int, default=None)
    parser.add_argument(
        "--wandb-watch-model",
        action="store_true",
        default=None,
    )
    parser.add_argument("--wandb-resume", type=str, default=None)
    parser.add_argument("--wandb-run-id", type=str, default=None)


def resolve_wandb_settings(args: Any, config: Mapping[str, Any]) -> dict[str, Any]:
    """Resolve CLI > YAML > environment > default W&B settings safely."""

    use_wandb = _as_bool(
        _config_value(args, config, "use_wandb", False, "USE_WANDB")
    )
    mode = str(
        _config_value(args, config, "wandb_mode", "online", "WANDB_MODE")
    ).lower()
    if mode not in {"online", "offline", "disabled"}:
        raise ValueError("wandb_mode must be one of: online, offline, disabled")

    tags = _config_value(args, config, "wandb_tags", [], "WANDB_TAGS")
    if isinstance(tags, str):
        tags = [item.strip() for item in tags.split(",") if item.strip()]
    else:
        tags = list(tags or [])

    # A plaintext key is intentionally never read from YAML. This prevents a
    # checked-in config or checkpoint config snapshot from becoming a secret
    # store. CLI takes priority over WANDB_API_KEY; absent both, W&B may use its
    # existing local login credentials.
    api_key = getattr(args, "wandb_api_key", None) or os.environ.get(
        "WANDB_API_KEY"
    )
    return {
        "enabled": use_wandb and mode != "disabled",
        "api_key": api_key or None,
        "project": _config_value(
            args, config, "wandb_project", "HMOE-SAM3", "WANDB_PROJECT"
        ),
        "entity": _config_value(
            args, config, "wandb_entity", None, "WANDB_ENTITY"
        )
        or None,
        "name": _config_value(args, config, "wandb_name", None, "WANDB_NAME")
        or None,
        "group": _config_value(
            args, config, "wandb_group", None, "WANDB_GROUP"
        )
        or None,
        "tags": tags or None,
        "mode": mode,
        "dir": _config_value(
            args, config, "wandb_dir", "./wandb", "WANDB_DIR"
        ),
        "log_interval": max(
            int(
                _config_value(
                    args,
                    config,
                    "wandb_log_interval",
                    10,
                    "WANDB_LOG_INTERVAL",
                )
            ),
            1,
        ),
        "watch_model": _as_bool(
            _config_value(
                args,
                config,
                "wandb_watch_model",
                False,
                "WANDB_WATCH_MODEL",
            )
        ),
        "resume": _config_value(
            args, config, "wandb_resume", "allow", "WANDB_RESUME"
        ),
        "run_id": _config_value(
            args, config, "wandb_run_id", None, "WANDB_RUN_ID"
        )
        or None,
    }


class WandbLogger:
    """Small rank-aware W&B facade that degrades to a safe no-op."""

    def __init__(
        self,
        settings: Mapping[str, Any],
        config: Mapping[str, Any],
        main_process: bool,
    ) -> None:
        self.enabled = False
        self.log_interval = int(settings.get("log_interval", 10))
        self._wandb = None
        self._run = None
        self._finished = False
        if not main_process or not settings.get("enabled", False):
            return

        try:
            import wandb
        except ImportError:
            warnings.warn(
                "W&B logging was enabled, but the wandb package is not installed. "
                "Install it with: pip install wandb",
                RuntimeWarning,
            )
            return

        try:
            mode = str(settings.get("mode", "online"))
            api_key = settings.get("api_key")
            if api_key and mode == "online":
                wandb.login(key=api_key)

            wandb_dir = Path(str(settings.get("dir", "./wandb")))
            wandb_dir.mkdir(parents=True, exist_ok=True)
            self._run = wandb.init(
                project=settings.get("project") or "HMOE-SAM3",
                entity=settings.get("entity") or None,
                name=settings.get("name") or None,
                group=settings.get("group") or None,
                tags=settings.get("tags") or None,
                mode=mode,
                dir=str(wandb_dir),
                config=sanitize_config(config),
                resume=settings.get("resume") or "allow",
                id=settings.get("run_id") or None,
            )
            self._wandb = wandb
            self.enabled = self._run is not None
        except Exception as error:
            warnings.warn(
                f"W&B initialization failed; training will continue without W&B "
                f"({type(error).__name__}).",
                RuntimeWarning,
            )
            self._wandb = None
            self._run = None
            self.enabled = False

    def log(self, metrics: Mapping[str, Any], step: int) -> None:
        if not self.enabled or self._wandb is None:
            return
        payload = flatten_metrics(metrics)
        if not payload:
            return
        try:
            self._wandb.log(payload, step=int(step))
        except Exception as error:
            warnings.warn(
                f"W&B metric logging failed and was disabled "
                f"({type(error).__name__}).",
                RuntimeWarning,
            )
            self.enabled = False

    def update_config(self, config: Mapping[str, Any]) -> None:
        if not self.enabled or self._run is None:
            return
        try:
            self._run.config.update(sanitize_config(config), allow_val_change=True)
        except Exception as error:
            warnings.warn(
                f"W&B config update failed ({type(error).__name__}).",
                RuntimeWarning,
            )

    def watch(self, model: torch.nn.Module) -> None:
        if not self.enabled or self._wandb is None:
            return
        try:
            self._wandb.watch(
                model,
                log="gradients",
                log_freq=max(self.log_interval, 100),
            )
        except Exception as error:
            warnings.warn(
                f"W&B model watch failed ({type(error).__name__}).",
                RuntimeWarning,
            )

    def finish(self) -> None:
        if self._finished:
            return
        self._finished = True
        if self._run is None:
            return
        try:
            self._run.finish()
        except Exception as error:
            warnings.warn(
                f"W&B finish failed ({type(error).__name__}).",
                RuntimeWarning,
            )
